// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "your_device_login_name"; // Your device login name

const char SSID[]               = "your_ssid";    // Network SSID (name)
const char PASS[]               = "your_password";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "your_device_key";    // Secret device password

void onCerenCountChange();
void onElaCountChange();
void onMeryemCountChange();
void onZeynepCountChange();

int cerenCount;
int elaCount;
int meryemCount;
int zeynepCount;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cerenCount, READWRITE, ON_CHANGE, onCerenCountChange);
  ArduinoCloud.addProperty(elaCount, READWRITE, ON_CHANGE, onElaCountChange);
  ArduinoCloud.addProperty(meryemCount, READWRITE, ON_CHANGE, onMeryemCountChange);
  ArduinoCloud.addProperty(zeynepCount, READWRITE, ON_CHANGE, onZeynepCountChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
